require("hamouda.plugins-setup")
require("hamouda.core.options")
require("hamouda.core.keymaps")
require("hamouda.core.colorscheme")
require("hamouda.plugins.comment")
require("hamouda.plugins.nvim-tree")
require("hamouda.plugins.lualine")
require("hamouda.plugins.telescope")
require("hamouda.plugins.nvim-cmp")
require("hamouda.plugins.gitsigns")
require("hamouda.plugins.autopairs")
require("hamouda.plugins.treesitter")
require("hamouda.plugins.lsp.mason")
require("hamouda.plugins.lsp.lspsaga")
require("hamouda.plugins.lsp.lspconfig")
require("hamouda.plugins.lsp.null-ls")

-- require("hamouda.plugins.copilot")
